### ISSUE TITLE
How to pass List as Extra?

### ISSUE THREAD

**Issue by aartikov** [FrantisekGazo/Blade#22]
I want to pass List<MyType> as Extra (MyType is Serializable). How can I do that?
I can use ArrayList instead of List, but I think that to use concreate implementation is not a good programming practice.

Could you please modify BundleWrapper, so it will support lists of serializable objects?

**Comment by FrantisekGazo** [comment]
Supporting just `List` would be tricky - e.g. if you initialized it with a custom implementation then you would expect to have it there after deserialization.

I could try to add a mechanism for custom serialization&deserialization of objects.

**Comment by FrantisekGazo** [comment]
@aartikov `v2.6.0-beta1` is out.

Now you can specify your own `Bundler` implementation for any object field.
e.g. `@Extra(MyListBundler.class) List<String> mList;`

Same goes for `@Arg` and `@State`.

You can try it give me feedback 😉

**Comment by aartikov** [comment]
Nice! It works.

This is my ListBundler:
```
public class ListBundler implements Bundler<List> {
	private static final String KEY = "key";

	@Override
	@SuppressWarnings("unchecked")
	public void save(@Nullable List value, @NonNull Bundle state) {
		if(value == null || value instanceof Serializable) {
			state.putSerializable(KEY, (Serializable) value);
		} else {
			state.putSerializable(KEY, new ArrayList(value));
		}
	}

	@Nullable
	@Override
	public List restore(@NonNull Bundle state) {
		return (List)state.getSerializable(KEY);
	}
}
```

**Comment by FrantisekGazo** [comment]
Ok, I'll just change the package name to `blade.Bundler` and if I don't find anything else I'll release it as `2.6.0`

**Comment by FrantisekGazo** [comment]
version `2.6.0` released
