### ISSUE TITLE
NoClassDefFoundError: javax/inject/Inject

### ISSUE THREAD

**Issue by sbalakin** [FrantisekGazo/Blade#42]
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: javax/inject/Inject

After including and downloading Blade

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'eu.f3rog.blade:plugin:2.7.0'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'blade'

**Comment by FrantisekGazo** [comment]
@sbalakin what's inside your `blade.yaml` file?
You most likely want to use `mvp` module but didn't add `dagger2` dependency.

**Comment by FrantisekGazo** [comment]
I'll look into it and add additional check that will show user a better error message if this happens.

**Comment by FrantisekGazo** [comment]
It's been added in version 2.7.1
