### ISSUE TITLE
Only Fragment subclass can contain @Arg with AndroidX

### ISSUE THREAD

**Issue by Grohden** [FrantisekGazo/Blade#54]
i'm getting this
```
/home/gabriel/projetos/mntng-android/app/build/tmp/kapt3/stubs/debug/br/com/ngi/mnt/ui/main/service/orders/OrdersPageFragment.java:12: error: Only Fragment subclass can contain @Arg.
public final class OrdersPageFragment extends br.com.ngi.mnt.base.BaseFragment implements br.com.ngi.mnt.ui.main.service.orders.contracts.OrdersPageView {
```
after migrating to AndroidX, i think that is cuz the fragment import changed from 
`import android.support.v4.app.Fragment`
to
`import androidx.fragment.app.Fragment`

And blade doesn't recognize the new package as a fragment

**Comment by Grohden** [comment]
Looking at the source i think that adding the fragment package here:
https://github.com/FrantisekGazo/Blade/blob/8f00bf5f8315ea5b7484a71f01a297bacdd0eff2/core-compiler/src/main/java/eu/f3rog/blade/compiler/name/ClassNames.java
like:
```java
ClassName AndroidXFragment = ClassName.get("androidx.fragment.app.Fragment", "Fragment");
```

And validating it here: https://github.com/FrantisekGazo/Blade/blob/8f00bf5f8315ea5b7484a71f01a297bacdd0eff2/core-compiler/src/main/java/eu/f3rog/blade/compiler/util/ProcessorUtils.java#L183-L185
with:
```java
public static boolean isFragmentSubClass(TypeElement inspectedType) {
        return isSubClassOf(inspectedType, Fragment.class) 
                || isSubClassOf(inspectedType, ClassNames.SupportFragment)
                || isSubClassOf(inspectedType, ClassNames.AndroidXFragment);
}
```

should solve the problem

**Comment by FrantisekGazo** [comment]
But sure, this is a relatively small thing, that I should fix quickly.

@Grohden thanks for the fix suggestion.

I will look at it today/tomorrow.

**Comment by Grohden** [comment]
I would do it myself, but i got some weird errors building the project (something about recyclerview version missing) :/

**Comment by FrantisekGazo** [comment]
@Grohden can you try version `2.7.2-beta3`? 

It should be working. (I also added some tests and tried it on a sample project, so it should be fine)

**Comment by Grohden** [comment]
@FrantisekGazo i can confirm that `2.7.2-beta3` is working with `args` and `extras`
