### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by rciurkot** [FrantisekGazo/Blade#8]
Hi,
I've tried to use this lib within my Kotlin project - to no avail.
Is it / will it be possible to use Blade with Kotlin? (Kotlin uses `kapt` instead of `aapt`)

**Comment by FrantisekGazo** [comment]
Hi, 
no this library does not support Kotlin classes. I'm planning to look at it. But I don't have time for it currently.

I don't use Kotlin, so it wasn't that important when I started this library.

If there is somebody who knows how to support `kapt` or about some open-source library that also supports `kapt` (from which I can inspire) - please leave a comment. thanks

**Comment by rciurkot** [comment]
It turns out that Blade and Kotlin can play well together :) You just have to enable generating stubs in `kapt`.
Put this in your `build.gradle` and everything should work fine.
```
kapt {
    generateStubs = true
}
```
Sometimes build is failing (InstantRun + kotlin incremental builds) but then simple clean-build action will make it work again.

Thanks @FrantisekGazo for such an awesome library :)

**Comment by FrantisekGazo** [comment]
@rciurkot that's great news. Thanks for sharing this solution :)

`Blade` is using `kapt` or `apt` based on found plugin - as you can see here: `https://github.com/FrantisekGazo/Blade/blob/master/plugin/src/main/groovy/eu/f3rog/blade/plugin/BladePlugin.groovy`. That is code I added when I started the library, but I was expecting that I will have to do something more.

@rciurkot did you try it with pure kotlin app or mixed java/kotlin?

**Comment by rciurkot** [comment]
Fortunately that line of code (selecting `kapt` or `apt`) was enough :)

I use it in mixed java/kotlin project with about 75% codebase in java. `Blade` is generating its classes for both java and kotlin code.
